### ISSUE TITLE
Container app with accelerator crashes

### ISSUE THREAD

**Issue by riccardopinosio** [microsoft/metered-billing-accelerator#162]
Hello,

I am not able to use the accelerator, perhaps someone can give me some pointers.

First, the readme of the deployment section is perhaps outdated, as the main-existing-rg.bicep script does not accept a tenantId parameter. Furthermore, the bicep deployment with deployAppInsights=false fails because no container app environment is created. So I modified the bicep scripts to create the container app environment together with the app insights etc by taking the code from the modules/environment.bicep file.

So far so good, I am able to create all the relevant resources in the resource group.

However, the container app with the aggregator crashes:

![image](https://github.com/microsoft/metered-billing-accelerator/assets/12471993/f392189a-bcb2-4d7c-b808-6bda1a69bc14)

The log stream reports:

![image](https://github.com/microsoft/metered-billing-accelerator/assets/12471993/92e13e79-0f9a-4f65-b1aa-de9500d3301d)

I am a bit at a loss on how to proceed, any pointers?

**Comment by chgeuer** [comment]
Hi @riccardopinosio , thanks for raising this. The accelerator needs AAD credentials to authenticate: the first one for the internal infrastructure (EventHub and storage account), the second cred to authenticate to the Azure Metered billing API. 

The console output looks like the accelerator not being able to authN towards EventHub. Would you mind sharing some insights on how your app container is configured? Are you using a managed identity to authN to your infra?

Happy to jump on a Teams call (my github alias (at) microsoft.com).

**Comment by riccardopinosio** [comment]
Hallo,

I am basically using this command:

az deployment group create --template-file main-existing-rg.bicep  \
      --parameters appNamePrefix=knightsmetered \
      --resource-group metered-billing-test \
      --parameters ADApplicationID=$azure_application_id_from_app_registration \
      --parameters ADObjectID=object_id_of_principal \
      --parameters ADApplicationSecret=$azure_application_secret \

It might be that I'm using some wrong parameter? What I use is:

- ADApplicationID:  I take this from the App registration
- ADApplicationSecret: I created a secret in the Certificates & secrets section of the App registration and put the secret here
- ADObjectID: I assigned the "contributor" role to the AAD application to the resource group where the resources are deployed, and then I put here the Object ID of the service principal

I would think the ADObjectID would take care of auth, but maybe I am mistaken?
I am using the deployment scripts in the deployment folder, in particular main-existing-rg.bicep, container-app.bicep, and data.bicep. I see these harcoded values in the latter:

`  roleDefinitions: {
    eventHub: {
      receiver:  'a638d3c7-ab3a-418d-83e6-5f17a39d4fde'
      sender:    '2b629674-e913-4c01-ae53-ef4638d8f975'
      dataOwner: 'f526a384-b230-433a-b45c-95f59c4a2dec'
    }
    blob: {
      contributor: 'ba92f5b4-2d11-453d-a403-e96b0029c9fe'
    }
  }`

Perhaps these need to be set?
I might take you up on the call offer, thanks!

**Comment by chgeuer** [comment]
@riccardopinosia and I sorted this out, it was an authorization config problem. The accelerator uses two credentials, one to talk to the local infrastructure (Event Hub and Blob storage), and a second one to talk to the metered billing API.
