### ISSUE TITLE
Errors in Bicep deployment scripts

### ISSUE THREAD

**Issue by danscarfe** [microsoft/metered-billing-accelerator#197]
Is it possible that main-new-rg.bicep and main-existing-rg.bicep have become out-of-step somehow?

![image](https://github.com/microsoft/metered-billing-accelerator/assets/4228651/1b909006-c2e0-4cb3-a935-3f560f22b2fd)

TenantId is missing as a parameter to the second script, you seem to access it directly in there now: 
![image](https://github.com/microsoft/metered-billing-accelerator/assets/4228651/c93bdddd-6251-45f7-aba7-383e7582d67f)

and the connectionstring output is just missing: 
![image](https://github.com/microsoft/metered-billing-accelerator/assets/4228651/213cbd46-f63f-4990-8d67-c21b664ff622)

**Comment by TaridaGeorge** [comment]
I'm having the same problem. The output of the script is as follows:

```
metered-billing-accelerator/deploy/modules/data.bicep(83,9) : Warning use-parent-property: Resource "captureContainer" has its name formatted as a child of resource "captureAndStateStorageAccount". The syntax can be simplified by using the parent property. [https://aka.ms/bicep/linter/use-parent-property]
metered-billing-accelerator/deploy/modules/data.bicep(87,9) : Warning use-parent-property: Resource "snapshotsContainer" has its name formatted as a child of resource "captureAndStateStorageAccount". The syntax can be simplified by using the parent property. [https://aka.ms/bicep/linter/use-parent-property]
metered-billing-accelerator/deploy/modules/data.bicep(91,9) : Warning use-parent-property: Resource "checkpointContainer" has its name formatted as a child of resource "captureAndStateStorageAccount". The syntax can be simplified by using the parent property. [https://aka.ms/bicep/linter/use-parent-property]
metered-billing-accelerator/deploy/modules/data.bicep(114,9) : Warning use-parent-property: Resource "eventHub" has its name formatted as a child of resource "eh_namespace". The syntax can be simplified by using the parent property. [https://aka.ms/bicep/linter/use-parent-property]
metered-billing-accelerator/deploy/main-new-rg.bicep(26,5) : Error BCP037: The property "tenantID" is not allowed on objects of type "params". Permissible properties include "AZURE_METERING_INFRA_CAPTURE_FILENAME_FORMAT", "containerImage", "containerRegistry", "containerRegistryUsername", "deployAppInsights", "eventHubSku", "isHnsEnabled", "isPrivateRegistry", "minReplicas", "registryPassword", "skuCapacity".
metered-billing-accelerator/deploy/main-new-rg.bicep(31,63) : Error BCP053: The type "outputs" does not contain property "eventHubConnectionString". Available properties include "eventHubName".
```

@danscarfe have you managed to fix it?

**Comment by danscarfe** [comment]
@TaridaGeorge I haven't played with it again since 😞

**Comment by danscarfe** [comment]
@TaridaGeorge in the end I just commented out the lines and it worked fine. The documentation is also wrong through. It wants an ADObjectID as a param too, which I think is the objectid of the security group that the sharedresourcebroker script creates. The script ran for me at least with that.

**Comment by chgeuer** [comment]
Thanks @TaridaGeorge and @danscarfe for reporting, I'll look into it this week, back from the holidays.

**Comment by chgeuer** [comment]
@TaridaGeorge, what type of Marketplace application are you having? Are you building a managed application, or a SaaS offer? 

![image](https://github.com/microsoft/metered-billing-accelerator/assets/795162/990c548b-8960-4de2-9620-5b9a39030fde)

Yesterday, I started a complete deployment walkthrough video series ([on YouTube](https://www.youtube.com/playlist?list=PLZv8EMzB61uVdnelyxIrVel3EXcGgyMNR)) for a managed app with central aggregation. In that, I effectively deploy using the `scripts/Metering.SharedResourceBroker/setup.sh` script to deploy the solution. The scripts `deploy/main-new-rg.bicep` is comparably old.

**Comment by chgeuer** [comment]
I think this is solved in the meantime.

**Comment by cveld** [comment]
@chgeuer maybe it is good to sprinkle a bit of additional deployment guidance into the documentation. I was first trying out the bicep stack (following `deploy/readme.md`) before I bumped into this issue. Now I will try out the `Metering.SharedResourceBroker` script
