### ISSUE TITLE
Aggregator container app problems

### ISSUE THREAD

**Issue by mwone-hw** [microsoft/metered-billing-accelerator#209]
Hi, I am experiencing similar issue to #162. I have commented but got no response so I'm opening this new issues. Please see the  details in my comment below:

Hi @chgeuer @riccardopinosio, I am encountering similar issues with the same error to the original post has stated. I have read the above thread and realized the solution has to do with setting up the two credentials (which I assume meant app registrations), but would like to ask for further instruction on how to configure them correctly. I am also open to Teams call if it makes life any easier. 

Similar to Riccardo, I have also made customization to the deployment scripts similar to what was mentioned in the original post. Here are the modifications I've made to the deployment scripts:
- Replaced API version from `2021-01-01-preview` to `2021-03-01` for the `Microsoft.App/containerApps` resource in [container-app.bicep line 21 and 25](https://github.com/microsoft/metered-billing-accelerator/blob/main/deploy/modules/container-app.bicep?plain=1#L21)
  - Seems to be the only difference between Riccardo's and my deployment process
  - API version `2021-01-01-preview` causes following error `{"code":"DeploymentFailed","target":"/subscriptions/00776c8c-f608-435e-b9c6-ece71415f2df/resourceGroups/hwmeteredbillingsandbox3-rg/providers/Microsoft.Resources/deployments/hwmeteredbillingsandbox3-container-app","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'uksouth' and API version '2022-01-01-preview' for type 'containerApps'. The supported api-versions are '2022-03-01, 2022-06-01-preview, 2022-10-01, 2022-11-01-preview, 2023-04-01-preview, 2023-05-01, 2023-05-02-preview, 2023-08-01-preview, 2023-11-02-preview'. The supported locations are 'northcentralusstage, westus2, southeastasia, swedencentral, canadacentral, westeurope, northeurope, eastus, eastus2, eastasia, australiaeast, germanywestcentral, japaneast, uksouth, westus, centralus, northcentralus, southcentralus, koreacentral, brazilsouth, westus3, francecentral, southafricanorth, norwayeast, switzerlandnorth, uaenorth, canadaeast, westcentralus, ukwest, centralindia'."}]}`
- Removed `if (deployAppInsights)` condition from [main-existing-rg.bicep line 107](https://github.com/microsoft/metered-billing-accelerator/blob/main/deploy/main-existing-rg.bicep?plain=1#L107)

After making the above modification, I attempted the deployment in the following steps:
1. Set up partner centre offer
2. Created one app registration and passed ID and secret to the partner centre offer ([following the managedAppIntegration guide](https://github.com/microsoft/metered-billing-accelerator/blob/main/src/Demos/ManagedAppIntegration/README.md?plain=1#L24))
3. Created new rg hwmeteredbillingsandbox4-rg, location UK South
4. Assign Blob contributor role to myself (deployer)
5. Assign contributor role to the app created in step 2
6. In Powershell console: Az login, select correct subscription, cd to deployment folder, run following deployment script:
  -  `az deployment group create --template-file main-existing-rg.bicep --parameters appNamePrefix=hwmeteredbillingsandbox4 --parameters ADApplicationID=<Step2AppID> --parameters ADApplicationSecret=<Step2AppSecret> --resource-group hwmeteredbillingsandbox4-rg`
  - Provided object ID of the application created in step 2 when prompted for ADObjectID
7. Encountered error stating "container app environment is not ready for container app creation as it is in state 'Waiting'", resolve by repeating step 6
8. All deployments are successful, but container app crashes
 ![image](https://github.com/microsoft/metered-billing-accelerator/assets/99651130/d1eff871-40a8-4805-931f-3c30813951c3)
 ![image](https://github.com/microsoft/metered-billing-accelerator/assets/99651130/535916fe-6c72-40cd-8c80-22c9176fadde)

[Here is a detailed container app crash log exported from Azure](https://github.com/microsoft/metered-billing-accelerator/files/14263573/query_data.csv)

Many thanks.

_Originally posted by @mwone-hw in https://github.com/microsoft/metered-billing-accelerator/issues/162#issuecomment-1941778065_

**Comment by chgeuer** [comment]
Hi @mwone-hw, looking into your CSV export, I see there's a problem getting a token for Azure.Messaging.EventHubs.Amqp.AmqpClient.xxx, i.e. the accelerator cannot talk to EventHubs. 

The accelerator expects 2 credentials:

- one that is configured in [Partnercenter to emit usage](https://github.com/microsoft/metered-billing-accelerator/?tab=readme-ov-file#azure-marketplace-api-credential-to-submit-metering-values-to-azure), (which is configured via the  `AZURE_METERING_MARKETPLACE_CLIENT_ID`/`AZURE_METERING_MARKETPLACE_CLIENT_SECRET`/`AZURE_METERING_MARKETPLACE_TENANT_ID` environment variables).
- The other one (which is used to talk to the infrastructure like storage and Event Hub) is the `AZURE_METERING_INFRA_CLIENT_ID`, `AZURE_METERING_INFRA_CLIENT_SECRET` and `AZURE_METERING_INFRA_TENANT_ID` credential...

So to me it looks like the instance doesn't successfully get the `AZURE_METERING_INFRA_...` bits

**Comment by mwone-hw** [comment]
Hi @chgeuer , thank you for the response.

Since I was aiming to use an UAMI for the credential, `AZURE_METERING_INFRA_CLIENT_ID`, `AZURE_METERING_INFRA_CLIENT_SECRET` and `AZURE_METERING_INFRA_TENANT_ID` was left empty as documentation instructed. I understand that it would be best practice to set up the solution with a service principal, but if I was to go down the route of using UAMI instead, is there any specific configuration I should be doing to my (the deployer's) user account?

Thank you again.

**Comment by chgeuer** [comment]
Hm. You're right, by not setting these 3 variables, the [code](https://github.com/microsoft/metered-billing-accelerator/blob/main/src/Metering.Runtime/InstanceMetadataClient.fs#L35) should be picking up the managed identity... Looking at the [docs](https://learn.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=portal%2Chttp), this looks correct to me.

**Comment by chgeuer** [comment]
Accidentally hit the "Close" button

**Comment by mwone-hw** [comment]
Please let me know if there is anything you might need from me to help with reproducing the issue. Thank you.

**Comment by chgeuer** [comment]
Hi @mwone-hw . Can you try to configure the submission with a 'traditional' service principal, instead of the managed identity?

**Comment by mwone-hw** [comment]
Hi @chgeuer, thank you for your response. 

I've successfully deployed with service principal and the container app did not crash.

The deployment was carried out following the exact steps outlined in the original post, with the only modification being the uncommenting of lines 88-90 in [main-existing-rg.bicep](https://github.com/microsoft/metered-billing-accelerator/blob/1c3c4fd9ff97be6fa2baf208e6ac495c21ca6f34/deploy/main-existing-rg.bicep#L88).
