### ISSUE TITLE
MeteredCollection Deserializtion failed if one meter was not used.

### ISSUE THREAD

**Issue by msalemcode** [microsoft/metered-billing-accelerator#95]
If plan has multiple metered dimensions and one of them is not used. Json type will fail to deserialize the file to MeteredCollection type.
Here is example 
{
   "lastProcessedMessage":{
      "partitionId":"0",
      "sequenceNumber":"17554",
      "partitionTimestamp":"2022-05-01T15:30:44.33Z"
   },
   "meters":{
      "2df36cb6-1d6e-48b7-d6f2-4f7dd52f7e0b":{
         "subscription":{
            "plan":{
               "planId":"privatemeter",
               "billingDimensions":{
                  "cpu1":0,
                  "cu":0,
                  "mem1":0
               
            },
            "renewalInterval":"Monthly",
            "subscriptionStart":"2022-04-24T02:10:00Z",
            "scope":"2df36cb6-1d6e-48b7-d6f2-4f7dd52f7e0b"
         },
         "metersMapping":{
            "cpu1":"cpu1",
            "cu":"cu",
            "mem1":"mem1"
         },
         "currentMeters":{
            "cpu1":{
               "consumed":{
                  "consumedQuantity":920.0,
                  "created":"2022-05-01T14:59:58.8805428Z",
                  "lastUpdate":"2022-05-01T15:30:44.33Z"
               }
            },
            **"cu":{
               "included":{
                  "monthly":0,
                  "annually":0,
                  "created":"2022-04-29T18:03:51.391Z",
                  "lastUpdate":"2022-04-29T18:03:51.391Z"
               }**
            },
            "mem1":{
               "consumed":{
                  "consumedQuantity":921.0,
                  "created":"2022-05-01T14:59:58.8805463Z",
                  "lastUpdate":"2022-05-01T15:30:44.33Z"
               }
            }
         },
         "usageToBeReported":[
            
         ],
         "lastProcessedMessage":{
            "partitionId":"0",
            "sequenceNumber":"17554",
            "partitionTimestamp":"2022-05-01T15:30:44.33Z"
         }
      }
   },
   "unprocessable":[
      
   ]
}

Notice Dimension **"cu"** was not used yet. If we attempt to deserialize this string will get the following exception
Error at: `$.meters.currentMeters`
Expecting an object with a field named `consumed` but instead got:
{
    "included": {
        "monthly": 0,
        "annually": 0,
        "created": "2022-04-29T18:03:51.391Z",
        "lastUpdate": "2022-04-29T18:03:51.391Z"
    },

However If we removed this unused dimension we get the successful result
{
   "lastProcessedMessage":{
      "partitionId":"0",
      "sequenceNumber":"17554",
      "partitionTimestamp":"2022-05-01T15:30:44.33Z"
   },
   "meters":{
      "2df36cb6-1d6e-48b7-d6f2-4f7dd52f7e0b":{
         "subscription":{
            "plan":{
               "planId":"privatemeter",
               "billingDimensions":{
                  "cpu1":"0",
                  "mem1":"0"
               }
            },
            "renewalInterval":"Monthly",
            "subscriptionStart":"2022-04-24T02:10:00Z",
            "scope":"2df36cb6-1d6e-48b7-d6f2-4f7dd52f7e0b"
         },
         "metersMapping":{
            "cpu1":"cpu1",
            "mem1":"mem1"
         },
         "currentMeters":{
            "cpu1":{
               "consumed":{
                  "consumedQuantity":920.0,
                  "created":"2022-05-01T14:59:58.8805428Z",
                  "lastUpdate":"2022-05-01T15:30:44.33Z"
               }
            },

            "mem1":{
               "consumed":{
                  "consumedQuantity":921.0,
                  "created":"2022-05-01T14:59:58.8805463Z",
                  "lastUpdate":"2022-05-01T15:30:44.33Z"
               }
            }
         },
         "usageToBeReported":[
            
         ],
         "lastProcessedMessage":{
            "partitionId":"0",
            "sequenceNumber":"17554",
            "partitionTimestamp":"2022-05-01T15:30:44.33Z"
         }
      }
   },
   "unprocessable":[
      
   ]
}
The above object will deserialized successfully

**Comment by chgeuer** [comment]
You're trying to parse an invalid data structure, where various fields have been randomly shuffled to different locations. This
 here is the valid structure:
 
 
 ```json
{
	"lastProcessedMessage": {
		"partitionId": "0",
		"sequenceNumber": "17554",
		"partitionTimestamp": "2022-05-01T15:30:44.33Z"
	},
	"meters": {
		"2df36cb6-1d6e-48b7-d6f2-4f7dd52f7e0b": {
			"subscription": {
				"plan": {
					"planId": "privatemeter",
					"billingDimensions": {
						"cpu1": 0,
						"cu": 0,
						"mem1": 0
					}
				},
				"renewalInterval": "Monthly",
				"subscriptionStart": "2022-04-24T02:10:00Z",
				"scope": "2df36cb6-1d6e-48b7-d6f2-4f7dd52f7e0b"
			},
			"metersMapping": {
				"cpu1": "cpu1",
				"cu": "cu",
				"mem1": "mem1"
			},
			"currentMeters": {
				"cpu1": {
					"consumed": {
						"consumedQuantity": 920.0,
						"created": "2022-05-01T14:59:58.8805428Z",
						"lastUpdate": "2022-05-01T15:30:44.33Z"
					}
				},
				"cu": {
					"included": {
						"quantity": 0,
						"created": "2022-04-29T18:03:51.391Z",
						"lastUpdate": "2022-04-29T18:03:51.391Z"
					}
				},
				"mem1": {
					"consumed": {
						"consumedQuantity": 921.0,
						"created": "2022-05-01T14:59:58.8805463Z",
						"lastUpdate": "2022-05-01T15:30:44.33Z"
					}
				}
			},
			"usageToBeReported": [],
			"lastProcessedMessage": {
				"partitionId": "0",
				"sequenceNumber": "17554",
				"partitionTimestamp": "2022-05-01T15:30:44.33Z"
			}
		}
	},
	"unprocessable": []
}
```
